# Generated by Django 3.2.8 on 2021-10-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alt',
            fields=[
                ('altId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('altLevel', models.PositiveSmallIntegerField()),
                ('altName', models.CharField(max_length=40)),
                ('altRealm', models.CharField(max_length=40)),
                ('altRealmId', models.PositiveSmallIntegerField()),
                ('altRealmSlug', models.CharField(max_length=40)),
                ('altClass', models.PositiveSmallIntegerField(choices=[(0, 'No Class'), (1, 'Warrior'), (2, 'Paladin'), (3, 'Hunter'), (4, 'Rogue'), (5, 'Priest'), (6, 'Death Knight'), (7, 'Shaman'), (8, 'Mage'), (9, 'Warlock'), (10, 'Monk'), (11, 'Druid'), (12, 'Demon Hunter')], default=0)),
                ('altRace', models.PositiveSmallIntegerField(choices=[(0, 'No Race'), (1, 'Human'), (2, 'Orc'), (3, 'Dwarf'), (4, 'Night Elf'), (5, 'Undead'), (6, 'Tauren'), (7, 'Gnome'), (8, 'Troll'), (9, 'Goblin'), (10, 'Blood Elf'), (11, 'Draenei'), (22, 'Worgen'), (24, 'Pandaren'), (25, 'Pandaren'), (26, 'Pandaren'), (27, 'Nightbourne'), (28, 'Highmountain Tauren'), (29, 'Void Elf'), (30, 'Lightforged Draenei'), (31, 'Zandalari Troll'), (32, 'Kul Tiran'), (34, 'Dark Iron Dwarf'), (35, 'Vulpera'), (36, "Mag'ar Orc"), (37, 'Mechagnome')], default=0)),
                ('altGender', models.CharField(max_length=6)),
                ('altFaction', models.CharField(max_length=10)),
                ('altExpiryDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'ft_alt',
            },
        ),
        migrations.AddConstraint(
            model_name='alt',
            constraint=models.UniqueConstraint(fields=('altName', 'altRealmSlug'), name='unique_alt'),
        ),
    ]
