# Generated by Django 3.2.8 on 2021-11-12 20:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apicore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileuser",
            name="userLastUpdate",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
