# Generated by Django 3.2.8 on 2021-10-15 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.PositiveSmallIntegerField(choices=[(0, 'Missing'), (171, 'Alchemy'), (164, 'Blacksmithing'), (333, 'Enchanting'), (202, 'Engineering'), (773, 'Inscription'), (755, 'Jewelcrafting'), (165, 'Leatherworking'), (197, 'Tailoring'), (182, 'Herbalism'), (186, 'Mining')], default=0)),
                ('professionData', models.JSONField()),
                ('altProfessionExpiryDate', models.DateTimeField()),
                ('alt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicore.alt')),
            ],
            options={
                'db_table': 'ft_altprofession',
            },
        ),
        migrations.AddConstraint(
            model_name='altprofession',
            constraint=models.UniqueConstraint(fields=('alt', 'profession'), name='unique_profession'),
        ),
    ]
