# Generated by Django 3.2.8 on 2021-10-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprofession',
            name='professionName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dataprofessionrecipe',
            name='recipeCategory',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dataprofessionrecipe',
            name='recipeName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dataprofessiontier',
            name='tierName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datareagent',
            name='reagentName',
            field=models.CharField(max_length=100),
        ),
    ]
