# Generated by Django 3.2.8 on 2021-10-15 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0002_auto_20211015_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltAchievement',
            fields=[
                ('alt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apicore.alt')),
                ('achievementData', models.JSONField()),
                ('altAchievementExpiryDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'ft_altachievement',
            },
        ),
        migrations.CreateModel(
            name='AltMedia',
            fields=[
                ('alt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apicore.alt')),
                ('avatar', models.CharField(default=None, max_length=100)),
                ('inset', models.CharField(default=None, max_length=100)),
                ('main', models.CharField(default=None, max_length=100)),
                ('mainRaw', models.CharField(default=None, max_length=100)),
                ('altMediaExpiryDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'ft_altmedia',
            },
        ),
        migrations.CreateModel(
            name='AltQuestCompleted',
            fields=[
                ('alt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apicore.alt')),
                ('questCompletedData', models.JSONField()),
                ('altQuestCompletedExpiryDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'ft_altquestcompleted',
            },
        ),
    ]
