# Generated by Django 3.2.8 on 2021-10-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0002_auto_20211026_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprofessionrecipe',
            name='recipeDescription',
            field=models.CharField(max_length=500),
        ),
    ]
