# Generated by Django 3.2.8 on 2021-11-22 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0003_dataspell'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSpell',
        ),
    ]
