# Generated by Django 3.2.8 on 2021-10-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0003_altachievement_altmedia_altquestcompleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('item_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('slot', models.CharField(max_length=20)),
                ('armour_type', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ft_equipment',
            },
        ),
        migrations.CreateModel(
            name='AltEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_level', models.PositiveSmallIntegerField()),
                ('stats', models.JSONField()),
                ('slot', models.CharField(max_length=20)),
                ('quality', models.CharField(max_length=20)),
                ('sockets', models.JSONField()),
                ('enchants', models.JSONField()),
                ('spells', models.JSONField()),
                ('azerite', models.JSONField()),
                ('altEquipmentExpiryDate', models.DateTimeField()),
                ('alt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicore.alt')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicore.equipment')),
            ],
            options={
                'db_table': 'ft_altequipment',
            },
        ),
    ]
