# Generated by Django 3.2.8 on 2021-10-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0003_alter_dataprofessionrecipe_recipedescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='datareagent',
            name='reagentMedia',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
