# Generated by Django 3.2.8 on 2021-10-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0004_datareagent_reagentmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datareagent',
            name='reagentMedia',
            field=models.CharField(max_length=150),
        ),
    ]
