# Generated by Django 3.2.8 on 2021-10-18 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0004_altequipment_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FazzToolsUser',
            fields=[
                ('userId', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ft_fazztoolsuser',
            },
        ),
        migrations.AddField(
            model_name='alt',
            name='user',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='apicore.fazztoolsuser'),
            preserve_default=False,
        ),
    ]
