# Generated by Django 5.2 on 2026-05-14 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apicore", "0004_delete_dataspell"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataPet",
            fields=[
                ("petId", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("petName", models.CharField(max_length=128)),
                ("petDescription", models.CharField(max_length=1024)),
                ("petSource", models.CharField(max_length=64)),
                ("petMediaIcon", models.CharField(max_length=256)),
                ("petFaction", models.CharField(max_length=64)),
                ("petNpcId", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "ft_data_pet",
            },
        ),
        migrations.AlterField(
            model_name="dataequipment",
            name="equipmentIcon",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="dataequipment",
            name="equipmentName",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="dataequipment",
            name="equipmentSlot",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="dataequipment",
            name="equipmentType",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="dataequipmentvariant",
            name="quality",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="dataequipmentvariant",
            name="variant",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="datamount",
            name="mountDescription",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="datamount",
            name="mountFaction",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="datamount",
            name="mountMediaIcon",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="datamount",
            name="mountMediaZoom",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="datamount",
            name="mountName",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="datamount",
            name="mountSource",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="dataprofession",
            name="professionDescription",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="dataprofession",
            name="professionName",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="dataprofessionrecipe",
            name="recipeCategory",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="dataprofessionrecipe",
            name="recipeDescription",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="dataprofessionrecipe",
            name="recipeName",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="dataprofessiontier",
            name="tierName",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="datareagent",
            name="reagentMedia",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="datareagent",
            name="reagentName",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="datareagent",
            name="reagentQuality",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="profilealt",
            name="altClass",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "No Class"),
                    (1, "Warrior"),
                    (2, "Paladin"),
                    (3, "Hunter"),
                    (4, "Rogue"),
                    (5, "Priest"),
                    (6, "Death Knight"),
                    (7, "Shaman"),
                    (8, "Mage"),
                    (9, "Warlock"),
                    (10, "Monk"),
                    (11, "Druid"),
                    (12, "Demon Hunter"),
                    (13, "Evoker"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="profilealt",
            name="altFaction",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="profilealt",
            name="altGender",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="profilealt",
            name="altName",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="profilealt",
            name="altRace",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "No Race"),
                    (1, "Human"),
                    (2, "Orc"),
                    (3, "Dwarf"),
                    (4, "Night Elf"),
                    (5, "Undead"),
                    (6, "Tauren"),
                    (7, "Gnome"),
                    (8, "Troll"),
                    (9, "Goblin"),
                    (10, "Blood Elf"),
                    (11, "Draenei"),
                    (22, "Worgen"),
                    (24, "Pandaren"),
                    (25, "Pandaren"),
                    (26, "Pandaren"),
                    (27, "Nightbourne"),
                    (28, "Highmountain Tauren"),
                    (29, "Void Elf"),
                    (30, "Lightforged Draenei"),
                    (31, "Zandalari Troll"),
                    (32, "Kul Tiran"),
                    (34, "Dark Iron Dwarf"),
                    (35, "Vulpera"),
                    (36, "Mag'ar Orc"),
                    (37, "Mechagnome"),
                    (52, "Dracthyr"),
                    (70, "Dracthyr"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="profilealt",
            name="altRealm",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="profilealt",
            name="altRealmSlug",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="profilealtequipment",
            name="back",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="profilealtequipment",
            name="belt",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="profilealtequipment",
            name="chest",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="profilealtequipment",
            name="feet",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="profilealtequipment",
            name="hands",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="profilealtequipment",
            name="head",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="profilealtequipment",
            name="legs",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="profilealtequipment",
            name="neck",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="profilealtequipment",
            name="ring1",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="profilealtequipment",
            name="ring2",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="profilealtequipment",
            name="shirt",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="profilealtequipment",
            name="shoulder",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="profilealtequipment",
            name="tabard",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="profilealtequipment",
            name="trinket1",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="profilealtequipment",
            name="trinket2",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="profilealtequipment",
            name="weapon1",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="profilealtequipment",
            name="weapon2",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="profilealtequipment",
            name="wrist",
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name="ProfileUserPet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apicore.datapet"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apicore.profileuser"
                    ),
                ),
            ],
            options={
                "db_table": "ft_profile_userpet",
            },
        ),
    ]
