# Generated by Django 3.2.8 on 2021-10-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0005_alter_datareagent_reagentmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMount',
            fields=[
                ('mountId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('mountName', models.CharField(max_length=100)),
                ('mountDescription', models.CharField(max_length=500)),
                ('mountSource', models.CharField(max_length=50)),
                ('mountMedia', models.CharField(max_length=150)),
                ('mountFaction', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ft_data_mount',
            },
        ),
    ]
