# Generated by Django 3.2.8 on 2021-10-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0005_auto_20211018_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altprofession',
            name='professionData',
            field=models.CharField(max_length=1000),
        ),
    ]
