# Generated by Django 5.2 on 2026-05-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apicore", "0006_alter_profilealt_altrace"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="profileusermount",
            constraint=models.UniqueConstraint(fields=("user", "mount"), name="unique_usermount"),
        ),
        migrations.AddConstraint(
            model_name="profileuserpet",
            constraint=models.UniqueConstraint(fields=("user", "pet"), name="unique_userpet"),
        ),
    ]
