# Generated by Django 3.2.8 on 2021-10-29 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0006_datamount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFazzToolsUser',
            new_name='ProfileUser',
        ),
        migrations.AlterModelTable(
            name='profileuser',
            table='ft_profile_user',
        ),
    ]
