# Generated by Django 3.2.8 on 2021-10-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0006_alter_altprofession_professiondata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='altprofession',
            old_name='profession',
            new_name='profession1',
        ),
        migrations.RemoveField(
            model_name='altprofession',
            name='professionData',
        ),
        migrations.AddField(
            model_name='altprofession',
            name='profession2',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Missing'), (171, 'Alchemy'), (164, 'Blacksmithing'), (333, 'Enchanting'), (202, 'Engineering'), (773, 'Inscription'), (755, 'Jewelcrafting'), (165, 'Leatherworking'), (197, 'Tailoring'), (182, 'Herbalism'), (186, 'Mining')], default=0),
        ),
    ]
