# Generated by Django 3.2.8 on 2021-10-21 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0007_auto_20211021_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altprofession',
            name='id',
        ),
        migrations.AlterField(
            model_name='altprofession',
            name='alt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apicore.alt'),
        ),
    ]
