# Generated by Django 3.2.8 on 2021-10-30 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0008_profileusermount'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profileusermount',
            table='ft_profile_usermount',
        ),
    ]
