# Generated by Django 3.2.8 on 2021-10-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0008_auto_20211021_0032'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='altprofession',
            name='unique_profession',
        ),
        migrations.AddConstraint(
            model_name='altprofession',
            constraint=models.UniqueConstraint(fields=('alt', 'profession1'), name='unique_profession'),
        ),
    ]
