# Generated by Django 3.2.8 on 2021-10-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0009_alter_profileusermount_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datamount',
            old_name='mountMedia',
            new_name='mountMediaIcon',
        ),
        migrations.AddField(
            model_name='datamount',
            name='mountMediaZoom',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
