# Generated by Django 5.2 on 2026-06-21 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apicore", "0009_dataprofessionrecipe_recipe_icon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataequipmentvariant",
            old_name="armour",
            new_name="armor",
        ),
    ]
