# Generated by Django 3.2.8 on 2021-10-21 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0009_auto_20211021_0032'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='altprofession',
            name='unique_profession',
        ),
    ]
