# Generated by Django 5.2 on 2026-05-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0009_dataprofessionrecipe_recipe_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprofessiontier',
            name='tier_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
