# Generated by Django 3.2.8 on 2021-11-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0010_auto_20211030_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilealt',
            name='altAccountId',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
