# Generated by Django 3.2.8 on 2021-10-21 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0010_remove_altprofession_unique_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altprofession',
            name='alt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apicore.alt'),
        ),
    ]
