# Generated by Django 5.2 on 2026-06-28 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0010_rename_armour_to_armor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAchievement',
            fields=[
                ('achievement_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('achievement_name', models.CharField(max_length=256)),
                ('achievement_points', models.PositiveSmallIntegerField(default=0)),
                ('achievement_category', models.CharField(default='', max_length=128)),
            ],
            options={
                'db_table': 'ft_data_achievement',
            },
        ),
        migrations.CreateModel(
            name='DataFaction',
            fields=[
                ('faction_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('faction_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'ft_data_faction',
            },
        ),
        migrations.CreateModel(
            name='ProfileAltAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_timestamp', models.DateTimeField(blank=True, null=True)),
                ('alt_achievement_expiry_date', models.DateTimeField()),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicore.dataachievement')),
                ('alt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicore.profilealt')),
            ],
            options={
                'db_table': 'ft_profile_altachievement',
                'constraints': [models.UniqueConstraint(fields=('alt', 'achievement'), name='unique_altachievement')],
            },
        ),
        migrations.CreateModel(
            name='ProfileAltReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standing_type', models.CharField(max_length=32)),
                ('standing_value', models.PositiveIntegerField()),
                ('alt_reputation_expiry_date', models.DateTimeField()),
                ('alt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicore.profilealt')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicore.datafaction')),
            ],
            options={
                'db_table': 'ft_profile_altreputation',
                'constraints': [models.UniqueConstraint(fields=('alt', 'faction'), name='unique_altreputation')],
            },
        ),
    ]
