# Generated by Django 5.2 on 2026-06-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0011_dataachievement_datafaction_profilealtachievement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilealtreputation',
            name='standing_value',
            field=models.IntegerField(),
        ),
    ]
