# Generated by Django 3.2.8 on 2021-10-21 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0011_alter_altprofession_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('professionId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('professionName', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'ft_profession',
            },
        ),
        migrations.CreateModel(
            name='ProfessionTier',
            fields=[
                ('tierId', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('tierName', models.CharField(max_length=25)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicore.profession')),
            ],
            options={
                'db_table': 'ft_professiontier',
            },
        ),
        migrations.CreateModel(
            name='ProfessionRecipe',
            fields=[
                ('recipeId', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('recipeName', models.CharField(max_length=50)),
                ('recipeDescription', models.CharField(max_length=250)),
                ('professionTier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicore.professiontier')),
            ],
            options={
                'db_table': 'ft_professionrecipe',
            },
        ),
        migrations.CreateModel(
            name='AltProfessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isKnown', models.BooleanField(default=False)),
                ('altProfession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicore.altprofession')),
                ('professionRecipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicore.professionrecipe')),
            ],
            options={
                'db_table': 'ft_altprofessiondata',
            },
        ),
    ]
