# Generated by Django 3.2.8 on 2021-10-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0012_altprofessiondata_profession_professionrecipe_professiontier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altprofession',
            name='profession1',
        ),
        migrations.AddField(
            model_name='altprofession',
            name='profession1',
            field=models.ManyToManyField(related_name='profession1', to='apicore.Profession'),
        ),
        migrations.RemoveField(
            model_name='altprofession',
            name='profession2',
        ),
        migrations.AddField(
            model_name='altprofession',
            name='profession2',
            field=models.ManyToManyField(related_name='profession2', to='apicore.Profession'),
        ),
    ]
