# Generated by Django 5.2 on 2026-06-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0012_alter_profilealtreputation_standing_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilealt',
            name='alt_ilvl',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
