# Generated by Django 3.2.8 on 2021-10-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0013_auto_20211021_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionrecipe',
            name='recipeDescription',
        ),
    ]
