# Generated by Django 5.2 on 2026-06-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0013_add_alt_ilvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafaction',
            name='faction_category',
            field=models.CharField(default='', max_length=128),
        ),
    ]
