# Generated by Django 5.2 on 2026-06-30 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0014_add_faction_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMythicDungeon',
            fields=[
                ('dungeon_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('dungeon_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'ft_data_mythicdungeon',
            },
        ),
        migrations.CreateModel(
            name='ProfileAltMythicPlus',
            fields=[
                ('alt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apicore.profilealt')),
                ('season_id', models.PositiveIntegerField()),
                ('mythic_rating', models.FloatField(default=0)),
                ('alt_mythicplus_expiry_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'ft_profile_altmythicplus',
            },
        ),
        migrations.CreateModel(
            name='ProfileAltMythicPlusDungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keystone_level', models.PositiveSmallIntegerField(default=0)),
                ('score', models.FloatField(default=0)),
                ('completed_timestamp', models.DateTimeField(blank=True, null=True)),
                ('is_completed_within_time', models.BooleanField(default=False)),
                ('alt_mythicplusdungeon_expiry_date', models.DateTimeField()),
                ('alt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicore.profilealtmythicplus')),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicore.datamythicdungeon')),
            ],
            options={
                'db_table': 'ft_profile_altmythicplusdungeon',
                'constraints': [models.UniqueConstraint(fields=('alt', 'dungeon'), name='unique_altmythicplusdungeon')],
            },
        ),
    ]
