# Generated by Django 3.2.8 on 2021-10-21 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0014_remove_professionrecipe_recipedescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altprofessiondata',
            name='altProfession',
        ),
        migrations.AddField(
            model_name='altprofessiondata',
            name='alt',
            field=models.ForeignKey(default=4124, on_delete=django.db.models.deletion.CASCADE, to='apicore.alt'),
            preserve_default=False,
        ),
    ]
