# Generated by Django 5.2 on 2026-06-30 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0015_datamythicdungeon_profilealtmythicplus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAltAddonData',
            fields=[
                ('alt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apicore.profilealt')),
                ('gold', models.PositiveBigIntegerField(default=0)),
                ('played_time_total', models.PositiveIntegerField(default=0)),
                ('played_time_level', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'ft_profile_altaddondata',
            },
        ),
    ]
