# Generated by Django 3.2.8 on 2021-10-21 21:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0016_auto_20211021_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altprofessiondata',
            name='isKnown',
        ),
        migrations.AddField(
            model_name='altprofessiondata',
            name='altProfessionDataExpiryDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='altprofessiondata',
            name='profession',
            field=models.ForeignKey(default=323, on_delete=django.db.models.deletion.CASCADE, to='apicore.profession'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='altprofessiondata',
            name='professionTier',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='apicore.professiontier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='altprofessiondata',
            name='alt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicore.altprofession'),
        ),
    ]
