# Generated by Django 3.2.8 on 2021-10-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0017_auto_20211021_2122'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='altprofessiondata',
            constraint=models.UniqueConstraint(fields=('alt', 'profession', 'professionTier', 'professionRecipe'), name='unique_altprofessiondata'),
        ),
    ]
