# Generated by Django 3.2.8 on 2021-10-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0018_altprofessiondata_unique_altprofessiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altprofession',
            name='profession1',
            field=models.PositiveIntegerField(choices=[(0, 'Missing'), (171, 'Alchemy'), (164, 'Blacksmithing'), (333, 'Enchanting'), (202, 'Engineering'), (773, 'Inscription'), (755, 'Jewelcrafting'), (165, 'Leatherworking'), (197, 'Tailoring'), (182, 'Herbalism'), (186, 'Mining'), (393, 'Skinning')], default=0),
        ),
        migrations.AlterField(
            model_name='altprofession',
            name='profession2',
            field=models.PositiveIntegerField(choices=[(0, 'Missing'), (171, 'Alchemy'), (164, 'Blacksmithing'), (333, 'Enchanting'), (202, 'Engineering'), (773, 'Inscription'), (755, 'Jewelcrafting'), (165, 'Leatherworking'), (197, 'Tailoring'), (182, 'Herbalism'), (186, 'Mining'), (393, 'Skinning')], default=0),
        ),
    ]
